apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cats
  description: The Cats is an app that exposes cat breeds through an API
  links:
    - url: https://github.com/northlander/cats
      title: GitHub Repo
      icon: github
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: cats
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=cats'
    github.com/project-slug: northlander/cats
    argocd/app-name: cats
spec:
  type: service
  lifecycle: production
  owner: cats-team
  system: pets
  providesApis:
    - cats-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cats-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    openapi: 3.0.0
    info:
      title: Cats
      description: Cats API
      version: 1.0.0
    servers:
      - url: http://cats.pets.fourmation.se
        description: main server
    paths:
      /:
        get:
          summary: Returns a list of cat breeds
          description: Not all cat breeds are included
          responses:
            '200':
              description: A JSON array of cat breeds
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string